### ISSUE TITLE
💡 [REQUEST] - Add Google Analytics Tracking

### ISSUE THREAD

**Issue by fgacyc** [fgacyc/whatsapp#10]
### Summary

Track User Visits

### Basic Example

 when user click `/page`, log an entry in GA

### General things to do

- [ ] Example: Track user actions and analytics with Google Analytics
- [ ] Create GA Account
- [ ] Link GA to Code
- [ ] Create Tracker
